schemaPath: src/schema.graphql
extensions:
  endpoints:
    default:
      url: https://api.github.com/graphql
      headers:
        Authorization: "Bearer ${env:GITHUB_TOKEN}"
  codegen:
    generator: binding-http
    source-schema: schema-with-import-statement.graphql